/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyExchange;

import CurrencyExchange.FileHandlers.*;
import CurrencyExchange.Users.AdminLogin;

import java.io.*;
import java.util.*;
import java.nio.file.*;
import processing.data.*;
import processing.core.*;



public class App extends PApplet{
    Json Json;
    AdminLogin AdminLogin;
    Database Database;

    @Override
    public void setup() {
        //initialise json file 
        String jsonFilepath = "src/main/java/resources/main/config.json";
        Json = new Json(loadJSONObject(jsonFilepath), jsonFilepath);

        //initialise database 
        String databaseFilePath = "src/main/java/resources/main/database.db";
        Database = new Database(databaseFilePath);

        //initialise admin login 
        String loginFilepath = "src/main/java/resources/main/admin.json";
        AdminLogin = new AdminLogin(loadJSONObject(loginFilepath), loginFilepath);

        Database.addCountry("bob", "AU", 1.24);
        Database.addCountry("bob", "UK", 2.34);
        Database.printAllRecords();

    }

    @Override
    public void draw() {

    }

    public static void main(String[] args) {
        PApplet.main("CurrencyExchange.App");
    }
}
