/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyExchange;

import CurrencyExchange.FileHandlers.*;

import java.io.*;
import java.util.*;
import java.nio.file.*;
import processing.data.*;
import processing.core.*;



public class App extends PApplet{
    Json Json;
    JSONObject jsonFile;

    @Override
    public void setup() {
        //initialise json file
        String jsonFilepath = "src/main/java/resources/main/config.json";
        Json = new Json(loadJSONObject(jsonFilepath), jsonFilepath);
    }

    @Override
    public void draw() {

    }

    public static void main(String[] args) {
        PApplet.main("CurrencyExchange.App");
    }
}